'use strict';
/* OpenResume Studio: self-contained browser resume editor. No service, account, or paywall. */
const STORAGE_KEY='openresume-studio-v1';
const $=sel=>document.querySelector(sel);
const uid=()=>`id_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xesc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const safeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#6554e8';
const glyphs={
 'file':'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h8"/>',
 'plus':'<path d="M12 5v14M5 12h14"/>','arrow-left':'<path d="m15 18-6-6 6-6M9 12h12"/>',
 'download':'<path d="M12 3v12m-4-4 4 4 4-4M5 17v3h14v-3"/>',
 'edit':'<path d="M12 20h9M16 4l4 4-12 12-4 1 1-4L17 5a2 2 0 0 1 3 3"/>',
 'layout':'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18"/>',
 'palette':'<circle cx="13.5" cy="6.5" r="1"/><circle cx="17.5" cy="10.5" r="1"/><circle cx="8" cy="7.5" r="1"/><circle cx="6" cy="12" r="1"/><path d="M12 22a10 10 0 1 1 10-10c0 4-3 4-6 4h-1a2 2 0 0 0-2 2c0 1 1 2 1 2 0 1-1 2-2 2Z"/>',
 'check':'<path d="m5 12 4 4L19 6"/>','check-circle':'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
 'alert':'<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>',
 'text':'<path d="M4 7h16M7 12h10M4 17h16"/>','grip':'<circle cx="9" cy="6" r="1"/><circle cx="15" cy="6" r="1"/><circle cx="9" cy="12" r="1"/><circle cx="15" cy="12" r="1"/><circle cx="9" cy="18" r="1"/><circle cx="15" cy="18" r="1"/>',
 'up':'<path d="m7 14 5-5 5 5"/>','down':'<path d="m7 10 5 5 5-5"/>','trash':'<path d="M3 6h18M8 6V4h8v2m3 0-1 14H6L5 6M10 10v6M14 10v6"/>',
 'copy':'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
 'eye':'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>','eye-off':'<path d="M3 3l18 18M10.7 5.1A11 11 0 0 1 12 5c6 0 10 7 10 7a17 17 0 0 1-3.1 3.7M6.4 6.4A18 18 0 0 0 2 12s4 7 10 7a10 10 0 0 0 4.6-1.1"/>',
 'user':'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 'briefcase':'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18"/>',
 'school':'<path d="m2 10 10-6 10 6-10 6-10-6ZM6 12v5c3 3 9 3 12 0v-5M22 10v7"/>',
 'mail':'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 6 10 7 10-7"/>',
 'phone':'<path d="M22 16.9v3a2 2 0 0 1-2.2 2A20 20 0 0 1 2 4.2 2 2 0 0 1 4 2h3a2 2 0 0 1 2 1.7l.5 3a2 2 0 0 1-.6 1.7L7 10a15 15 0 0 0 7 7l1.6-1.9a2 2 0 0 1 1.7-.6l3 .5a2 2 0 0 1 1.7 1.9Z"/>',
 'pin':'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 'link':'<path d="M10 13a5 5 0 0 0 7 .5l3-3a5 5 0 0 0-7-7l-1.7 1.7M14 11a5 5 0 0 0-7-.5l-3 3a5 5 0 0 0 7 7l1.7-1.7"/>',
 'close':'<path d="M18 6 6 18M6 6l12 12"/>', 'chevron':'<path d="m9 18 6-6-6-6"/>',
 'sparkle':'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>',
 'settings':'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
 'folder':'<path d="M3 7a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v9H3Z"/>',
 'external':'<path d="M14 3h7v7M10 14 21 3M20 14v6H4V4h6"/>',
 'save':'<path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2Z M7 3v6h9V3M7 21v-8h10v8"/>',
 'document':'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M8 7h8M8 11h8M8 15h6"/>',
 'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4m11.4-11.4 1.4-1.4"/>',
 'menu':'<path d="M4 6h16M4 12h16M4 18h16"/>',
 'upload':'<path d="M12 17V3m-5 5 5-5 5 5M4 17v4h16v-4"/>'};
const icon=(name,size=17)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${glyphs[name]||glyphs.file}</svg>`;
const sectionDefs=[
 ['summary','Professional summary','summary','main'],['experience','Work experience','timeline','main'],['education','Education','timeline','main'],['projects','Projects','timeline','main'],['skills','Skills','tags','side'],['certifications','Certifications','compact','side'],['languages','Languages','compact','side'],['volunteering','Volunteering','timeline','main'],['awards','Awards','compact','side'],['achievements','Key achievements','compact','side'],['courses','Courses','compact','side'],['publications','Publications','compact','main'],['interests','Interests','tags','side'],['custom','Custom section','summary','main']];
const lookupType=t=>sectionDefs.find(x=>x[0]===t)||sectionDefs.at(-1);
const defaultItem=kind=>kind==='timeline'?{title:'',subtitle:'',location:'',start:'',end:'',details:''}:kind==='compact'?{title:'',subtitle:'',date:'',details:''}:{text:''};
function newSection(type){const def=lookupType(type);return{id:uid(),type:def[0],kind:def[2],title:def[1],column:def[3],visible:true,items:[defaultItem(def[2])]};}
const demoContact={fullName:'Alex Morgan',headline:'Software Engineer',email:'alex.morgan@email.com',phone:'(555) 321-9876',location:'Austin, TX',website:'alexmorgan.dev',linkedin:'linkedin.com/in/alexmorgan',github:'github.com/alexmorgan'};
function demoDocument(){
 const secs=[newSection('summary'),newSection('experience'),newSection('education'),newSection('projects'),newSection('skills'),newSection('certifications')];
 secs[0].items=[{text:'Software engineer with 4+ years of experience building reliable web applications and developer tools. Skilled in TypeScript, Python, React, and cloud platforms. Passionate about improving performance, accessibility, and user experience.'}];
 secs[1].items=[{title:'Software Engineer',subtitle:'Northstar Technologies',location:'Austin, TX',start:'Jan 2023',end:'Present',details:'Built and launched internal tooling used by 1,200+ employees, reducing support requests by 35%.\nImproved API response times by 42% through query optimization and caching.\nCollaborated with designers and product teams to ship accessible React features.'},{title:'Software Developer',subtitle:'Brightwave Labs',location:'Remote',start:'Jun 2021',end:'Dec 2022',details:'Developed customer-facing features in React and Node.js for 50,000+ monthly users.\nCreated automated test pipelines that reduced deployment issues by 28%.'}];
 secs[2].items=[{title:'B.S. in Computer Science',subtitle:'University of Texas at Austin',location:'Austin, TX',start:'2017',end:'2021',details:'Relevant coursework: Algorithms, Databases, Software Engineering'}];
 secs[3].items=[{title:'Open-source Task Manager',subtitle:'React · TypeScript · PostgreSQL',location:'',start:'2024',end:'',details:'Designed a responsive productivity app with real-time collaboration and role-based access.\nImplemented CI/CD workflows and comprehensive integration tests.'}];
 secs[4].items=[{text:'TypeScript, JavaScript, React, Node.js, Python, SQL, PostgreSQL, Git, AWS, Docker, REST APIs, Unit Testing'}];
 secs[5].items=[{title:'AWS Certified Cloud Practitioner',subtitle:'Amazon Web Services',date:'2024',details:''}];
 return{id:uid(),title:'Software Engineer Resume',updated:Date.now(),contact:{...demoContact},template:'split',accent:'#6554e8',font:'sans',fontSize:12,density:'normal',headingCase:'upper',paper:'letter',sections:secs};
}
function blankDocument(){const secs=['summary','experience','education','skills'].map(newSection);return{id:uid(),title:'Untitled resume',updated:Date.now(),contact:Object.fromEntries(Object.keys(demoContact).map(k=>[k,''])),template:'clean',accent:'#6554e8',font:'sans',fontSize:12,density:'normal',headingCase:'upper',paper:'letter',sections:secs};}
function readStore(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));if(data&&Array.isArray(data.docs))return data;}catch(e){console.warn('Local storage unavailable or invalid:',e)}return{docs:[demoDocument()],currentId:null};}
let store=readStore();let activeId=null;let tab='content';let openSection=null;let zoomSetting='fit';let mobilePreview=false;let modalName=null;let toastTimer;
const doc=()=>store.docs.find(x=>x.id===activeId)||null;
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(store));}catch(e){showToast('Could not save: browser storage may be full. Export a JSON backup.');}}
function changed(){if(doc())doc().updated=Date.now();persist();const el=$('.save-label');if(el)el.innerHTML=`${icon('check-circle',13)} Saved locally`;}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2800);}
function minipaper(d){return`<div class="mini-paper" style="--mini-accent:${safeColor(d.accent)}"><div class="mini-head"></div><div class="mini-sub"></div><div class="mini-line md"></div><div class="mini-line sm"></div><div class="mini-title"></div>${Array.from({length:6},(_,i)=>`<div class="mini-line ${i%3===0?'md':i%4===0?'sm':''}"></div>`).join('')}<div class="mini-title"></div>${Array.from({length:6},(_,i)=>`<div class="mini-line ${i%2?'md':''}"></div>`).join('')}</div>`;}
function renderDashboard(){activeId=null;modalName=null;document.title='My resumes — OpenResume Studio';const list=store.docs.slice().sort((a,b)=>b.updated-a.updated);$('#app').innerHTML=`
 <header class="site-top"><div class="brand"><span class="brand-mark">${icon('file',20)}</span> OpenResume <span style="color:var(--purple)">Studio</span></div><div class="site-right"><span>No sign-up. No subscription.</span><span class="pill green">${icon('check',13)} 100% free</span></div></header>
 <main class="dash-main"><div class="dash-hero"><div><div class="eyebrow">Your creative workspace</div><h1>Make your next move<br>look great.</h1><p>Build professional, job-ready resumes your way. Everything stays in your browser.</p></div><button class="btn primary" data-action="newResume">${icon('plus',18)} Create new resume</button></div>
 <div class="dash-toolbar"><h2>My resumes <span class="count">${store.docs.length} document${store.docs.length===1?'':'s'}</span></h2><button class="btn white sm" data-action="import">${icon('upload',15)} Import backup</button></div>
 <div class="resume-grid"><button class="new-card" data-action="newResume"><span class="new-icon">${icon('plus',27)}</span><strong>Start a new resume</strong><span>Choose a template and make it your own.<br>No limits, ever.</span></button>
 ${list.map(d=>`<article class="resume-card"><div class="card-preview" data-action="editResume" data-id="${esc(d.id)}">${minipaper(d)}<span class="card-shine">${esc(d.template.charAt(0).toUpperCase()+d.template.slice(1))}</span></div><div class="resume-card-body"><h3>${esc(d.title)}</h3><p>Edited ${new Date(d.updated).toLocaleDateString()} · ${d.sections.length} sections</p><div class="card-actions"><button class="btn soft sm" data-action="editResume" data-id="${esc(d.id)}">${icon('edit',14)} Edit resume</button><div class="card-action-group"><button class="icon-btn" title="Duplicate" aria-label="Duplicate resume" data-action="duplicate" data-id="${esc(d.id)}">${icon('copy',15)}</button><button class="icon-btn" title="Delete" aria-label="Delete resume" data-action="deleteResume" data-id="${esc(d.id)}">${icon('trash',15)}</button></div></div></div></article>`).join('')}</div>
 <p class="footer-note">All resume content is saved locally on this device. Export a JSON backup to keep a portable copy.</p></main>`;
}
const tabs=[['content','text','Content'],['sections','layout','Sections'],['templates','file','Templates'],['design','palette','Design'],['check','check-circle','ATS check'],['export','download','Export']];
function renderEditor(){if(!doc())return renderDashboard();document.title=`${doc().title} — OpenResume Studio`;$('#app').innerHTML=`<div class="editor-shell">
<header class="editor-top"><div class="brand"><span class="brand-mark">${icon('file',19)}</span><span class="brand-text">OpenResume <span style="color:var(--purple)">Studio</span></span></div><div class="top-middle"><button class="btn ghost sm hide-mobile" data-action="dashboard">${icon('arrow-left',15)} All resumes</button><input class="filename" aria-label="Resume file name" data-object="document" data-key="title" maxlength="80" value="${esc(doc().title)}"><span class="save-label">${icon('check-circle',13)} Saved locally</span></div><div class="top-actions"><button class="btn white sm hide-mobile" data-action="duplicate" data-id="${esc(doc().id)}">${icon('copy',15)} Duplicate</button><button class="btn white sm" data-action="mobilePreview">${icon('eye',15)} <span class="hide-mobile">Preview</span></button><button class="btn primary sm" data-action="setTab" data-tab="export">${icon('download',16)} Download</button></div></header>
<div class="editor-body ${mobilePreview?'mobile-preview':''}"><nav class="tool-rail" aria-label="Editor tools">${tabs.map(([id,ico,title])=>`<button class="rail-item ${tab===id?'active':''}" data-action="setTab" data-tab="${id}" title="${title}">${icon(ico,21)}<span>${title}</span></button>`).join('')}<div class="rail-spacer"></div><button class="rail-item" data-action="dashboard" title="All resumes">${icon('arrow-left',21)}<span>Back</span></button></nav><aside class="panel"><div class="panel-head" id="panelHead"></div><div class="panel-scroll" id="panelContent"></div><div class="panel-footer" id="panelFooter"></div></aside><section class="workspace" aria-label="Live resume preview"><div class="work-top"><div class="left">${icon('eye',15)} <strong>Live preview</strong> <span class="pill green">Auto-saved</span></div><div class="right"><span id="pageLabel">US Letter</span><button class="zoom-btn" data-action="zoomOut" title="Zoom out">−</button><strong id="zoomLabel">Fit</strong><button class="zoom-btn" data-action="zoomIn" title="Zoom in">+</button></div></div><div class="paper-scroller" id="paperScroller"><div class="paper-holder" id="paperHolder"><article class="resume-paper" id="resumePaper"></article></div></div></section></div></div>`;renderPanel();renderPreview();requestAnimationFrame(syncZoom);}
function renderPanel(){const titles={content:['Edit content','Click a section to edit its details. Changes appear instantly.'],sections:['Manage sections','Show, hide, reorder, or reposition sections.'],templates:['Choose a template','Switch layouts without losing your content.'],design:['Design & font','Fine-tune the look and feel of your resume.'],check:['Resume checker','Practical writing and keyword checks, not a real ATS result.'],export:['Download & backup','Your resume is yours. Download it any time.']};const [title,desc]=titles[tab];$('#panelHead').innerHTML=`<h2>${title}</h2><p>${desc}</p>`;$('#panelContent').innerHTML=({content:contentPanel,sections:sectionsPanel,templates:templatesPanel,design:designPanel,check:checkPanel,export:exportPanel})[tab]();$('#panelFooter').innerHTML=tab==='content'||tab==='sections'?`<button class="btn soft" data-action="openAddModal">${icon('plus',17)} Add a section</button>`:tab==='export'?`<button class="btn white" data-action="import">${icon('upload',16)} Import JSON backup</button>`:tab==='check'?`<button class="btn white" data-action="setTab" data-tab="content">${icon('edit',15)} Improve content</button>`:`<button class="btn white" data-action="setTab" data-tab="content">${icon('check',15)} Continue editing</button>`;}
function field(label,obj,key,value,extra=''){const multi=extra.includes('multiline');const options=extra.includes('rows=')?extra.match(/rows=(\d+)/)?.[1]:3;return`<label class="field"><span>${esc(label)}</span>${multi?`<textarea rows="${options}" data-object="${obj}" data-key="${key}" ${extra.replace(/multiline|rows=\d+/g,'')}>${esc(value)}</textarea>`:`<input data-object="${obj}" data-key="${key}" value="${esc(value)}" ${extra}>`}</label>`;}
function itemField(label,sid,i,key,value,multi=false){return`<label class="field"><span>${esc(label)}</span>${multi?`<textarea rows="3" data-object="item" data-sid="${sid}" data-index="${i}" data-key="${key}" placeholder="One bullet per line">${esc(value)}</textarea>`:`<input data-object="item" data-sid="${sid}" data-index="${i}" data-key="${key}" value="${esc(value)}">`}</label>`;}
function sectionEditor(s){return`<div class="edit-section ${openSection===s.id?'open':''}" id="edit-${s.id}"><div class="edit-section-top" data-action="toggleSection" data-sid="${s.id}"><div class="part">${icon(lookupType(s.type)[2]==='timeline'?'briefcase':s.kind==='tags'?'layout':'file',16)}<div><strong>${esc(s.title)}</strong><small>${s.items.length} entr${s.items.length===1?'y':'ies'} · ${esc(s.column==='side'?'Sidebar':'Main')}</small></div></div>${icon(openSection===s.id?'down':'chevron',15)}</div>${openSection!==s.id?'':`<div class="edit-section-content">${field('Section heading','section','title',s.title,`data-sid="${s.id}"`)}${s.items.map((item,i)=>`<div class="entry-edit"><div class="entry-edit-bar"><strong>${esc(item.title||item.text?.slice(0,28)||`Entry ${i+1}`)}</strong><div class="tools"><button class="icon-btn" title="Move up" data-action="moveEntry" data-sid="${s.id}" data-index="${i}" data-direction="-1" ${i===0?'disabled':''}>${icon('up',14)}</button><button class="icon-btn" title="Move down" data-action="moveEntry" data-sid="${s.id}" data-index="${i}" data-direction="1" ${i===s.items.length-1?'disabled':''}>${icon('down',14)}</button><button class="icon-btn" title="Remove entry" data-action="removeEntry" data-sid="${s.id}" data-index="${i}">${icon('trash',13)}</button></div></div>${entryFields(s,item,i)}</div>`).join('')}<button class="add-entry" data-action="addEntry" data-sid="${s.id}">+ Add entry</button></div>`}</div>`;}
function entryFields(s,item,i){const base=(label,key,multi=false)=>itemField(label,s.id,i,key,item[key]||'',multi);
 if(s.kind==='summary')return base(s.type==='summary'?'Professional summary':'Description','text',true);
 if(s.kind==='tags')return base('Items (separate with commas)','text',true);
 if(s.kind==='compact')return`${base('Name / title','title')}${base('Organization / detail','subtitle')}${base('Date or level','date')}${base('Description (optional)','details',true)}`;
 const isEdu=s.type==='education';const isProj=s.type==='projects';return`${base(isEdu?'Degree / qualification':isProj?'Project name':'Position / role','title')}${base(isEdu?'School / university':isProj?'Technology / affiliation':'Company / organization','subtitle')}${base('Location (optional)','location')}<div class="fields-2">${base('Start date','start')}${base('End date','end')}</div>${base('Highlights (one bullet per line)','details',true)}`;}
function contentPanel(){const c=doc().contact;return`<p class="panel-titleline">Personal details</p><div class="fields-2">${field('Full name','contact','fullName',c.fullName)}${field('Job title','contact','headline',c.headline)}</div>${field('Email','contact','email',c.email,'type="email"')}<div class="fields-2">${field('Phone','contact','phone',c.phone)}${field('Location','contact','location',c.location)}</div>${field('Website / portfolio','contact','website',c.website)}${field('LinkedIn','contact','linkedin',c.linkedin)}${field('GitHub','contact','github',c.github)}<div class="divider-space"></div><p class="panel-titleline">Resume sections</p>${doc().sections.map(sectionEditor).join('')}`;}
function sectionsPanel(){return`<div class="info-card"><strong style="font-size:12px">Organize your story</strong><p>Move sections up or down; use the column selector for two-column designs. Hidden sections are retained for later.</p></div>${doc().sections.map((s,i)=>`<div class="section-list-item ${s.visible?'':'disabled'}"><span style="color:#aaa5bc">${icon('grip',16)}</span><div class="section-detail"><strong>${esc(s.title)}</strong><select aria-label="Column for ${esc(s.title)}" data-object="section" data-key="column" data-sid="${s.id}" style="font-size:10px;padding:5px;width:105px"><option value="main" ${s.column==='main'?'selected':''}>Main column</option><option value="side" ${s.column==='side'?'selected':''}>Side column</option></select></div><div class="tools"><button class="icon-btn" title="Move up" data-action="moveSection" data-sid="${s.id}" data-direction="-1" ${i===0?'disabled':''}>${icon('up',14)}</button><button class="icon-btn" title="Move down" data-action="moveSection" data-sid="${s.id}" data-direction="1" ${i===doc().sections.length-1?'disabled':''}>${icon('down',14)}</button><button class="icon-btn" title="${s.visible?'Hide':'Show'}" data-action="toggleVisibility" data-sid="${s.id}">${icon(s.visible?'eye':'eye-off',14)}</button><button class="icon-btn" title="Delete section" data-action="removeSection" data-sid="${s.id}">${icon('trash',14)}</button></div></div>`).join('')}`;}
function thumb(t){return`<div class="template-thumb ${t}"><div class="tt-name"></div><div class="tt-role"></div><div class="thumb-content"><div><div class="tt-rule"></div><div class="tt-line"></div><div class="tt-line short"></div><div class="tt-line"></div><div class="tt-rule"></div><div class="tt-line"></div></div>${t==='split'?`<div><div class="tt-rule"></div><div class="tt-line"></div><div class="tt-line short"></div><div class="tt-rule"></div><div class="tt-line"></div></div>`:''}</div></div>`;}
function templatesPanel(){return`<p class="panel-titleline">Resume layouts</p><div class="template-list">${[['split','Modern split','Two columns'],['clean','Clean & bold','Single column'],['classic','Classic','Traditional'],['minimal','Minimal','ATS-focused']].map(([t,title,desc])=>`<button class="template-option ${doc().template===t?'selected':''}" data-action="setTemplate" data-value="${t}">${thumb(t==='minimal'?'classic':t)}<strong>${title}${doc().template===t?` <span style="color:var(--purple)">✓</span>`:''}</strong><small>${desc}</small></button>`).join('')}</div><div class="info-card" style="margin-top:19px"><strong style="font-size:12px">Tip for applicant tracking systems</strong><p>A conventional single-column layout is the safest choice for older ATS parsers. Your Word export is always single-column.</p></div>`;}
const accents=['#6554e8','#262a55','#3174b9','#219e8b','#dc7461','#bd5591','#333333','#a77838'];
function designPanel(){return`<p class="panel-titleline">Accent color</p><div class="color-swatches">${accents.map(c=>`<button class="swatch ${doc().accent===c?'selected':''}" style="background:${c}" title="${c}" data-action="setAccent" data-value="${c}"></button>`).join('')}</div>${field('Custom hex color','document','accent',doc().accent)}<div class="divider-space"></div><p class="panel-titleline">Typography</p><label class="field"><span>Font family</span><select data-object="document" data-key="font"><option value="sans" ${doc().font==='sans'?'selected':''}>Arial / modern sans</option><option value="modern" ${doc().font==='modern'?'selected':''}>Trebuchet / humanist</option><option value="serif" ${doc().font==='serif'?'selected':''}>Georgia / serif</option></select></label><label class="field"><span>Base font size</span><select data-object="document" data-key="fontSize">${[10,11,12,13,14].map(n=>`<option value="${n}" ${Number(doc().fontSize)===n?'selected':''}>${n} px preview</option>`).join('')}</select></label><div class="divider-space"></div><p class="panel-titleline">Spacing</p><div class="choice-row">${[['compact','Compact'],['normal','Normal'],['spacious','Airy']].map(([v,txt])=>`<button data-action="setDensity" data-value="${v}" class="${doc().density===v?'selected':''}">${txt}</button>`).join('')}</div><div class="divider-space"></div><p class="panel-titleline">Paper</p><div class="choice-row">${[['letter','US Letter'],['a4','A4']].map(([v,txt])=>`<button data-action="setPaper" data-value="${v}" class="${doc().paper===v?'selected':''}">${txt}</button>`).join('')}</div><div class="divider-space"></div><p class="panel-titleline">Section headings</p><div class="choice-row">${[['upper','UPPERCASE'],['natural','Title case']].map(([v,txt])=>`<button data-action="setCase" data-value="${v}" class="${doc().headingCase===v?'selected':''}">${txt}</button>`).join('')}</div>`;}
function getPlainText(d){const parts=[...Object.values(d.contact)];d.sections.filter(s=>s.visible).forEach(s=>{parts.push(s.title);s.items.forEach(item=>parts.push(...Object.values(item)))});return parts.join('\n');}
function analyze(){const d=doc(),text=getPlainText(d),get=t=>d.sections.find(s=>s.type===t&&s.visible&&s.items.length);const experience=get('experience');const bullets=experience?.items.some(it=>(it.details||'').split('\n').filter(v=>v.trim().length>7).length>=2);
 const tests=[
 ['Your name is present',d.contact.fullName.trim().length>2,'Add your first and last name.'],
 ['Professional headline',d.contact.headline.trim().length>3,'Include the role you are targeting.'],
 ['Contact email',/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.contact.email.trim()),'Use a valid contact email.'],
 ['Phone or profile link',!!(d.contact.phone||d.contact.linkedin||d.contact.website),'Add a phone number or professional profile.'],
 ['Clear professional summary',!!get('summary')&&(get('summary').items[0]?.text||'').trim().length>=65,'Write a 2–3 sentence summary of your value.'],
 ['Experience section',!!experience&&experience.items.some(x=>x.title.trim()),'Add a work experience entry.'],
 ['Achievement bullets',!!bullets,'Use at least two impact-focused bullets.'],
 ['Quantified impact',/\b\d+[\d,.]*\s*(%|\+|k|m|million|users|hours|projects|people|employees|customers|times)?\b/i.test(experience?.items.map(x=>x.details).join(' ')||''),'Add outcomes with numbers or measurable results.'],
 ['Education section',!!get('education')&&get('education').items.some(x=>x.title.trim()),'Add education or relevant training.'],
 ['Skills section',!!get('skills')&&get('skills').items.some(x=>x.text.trim()),'Include skills relevant to the role.']];return{tests,score:Math.round(tests.filter(x=>x[1]).length/tests.length*100),text};}
const stopWords=new Set('a an the and or to of in on at for from with by as is are be been being will would can could should this that your you our their we they an how about into over under across also it its these those some any must required preferred experience knowledge ability strong excellent looking work role team years including using use skills understanding position candidate responsibilities qualifications job apply please what who which more have has using technical provide'.split(' '));
function jobKeywords(ad,resume){const words=(ad.toLowerCase().match(/[a-z][a-z0-9+.#/-]{2,}/g)||[]).filter(w=>!stopWords.has(w)&&!/^\d+$/.test(w));const count={};for(const w of words)count[w]=(count[w]||0)+1;const filtered=Object.entries(count).sort((a,b)=>b[1]-a[1]).slice(0,18).map(([word])=>word);const lower=resume.toLowerCase();return filtered.map(word=>({word,match:lower.includes(word)}));}
let jobText='';
function checkPanel(){const a=analyze();const kws=jobText?jobKeywords(jobText,a.text):[];return`<div class="score-gauge"><div class="score-dial" style="--fill:${a.score}%"><div>${a.score}<small>/ 100</small></div></div><div><h3>${a.score>=80?'Looking good!':a.score>=60?'Good start':'Room to improve'}</h3><p>Estimated completeness based on 10 common resume-writing checks. Not an ATS pass score.</p></div></div><p class="panel-titleline">Content checklist</p>${a.tests.map(([label,pass,tip])=>`<div class="check-item ${pass?'pass':'fail'}">${icon(pass?'check-circle':'alert',17)}<div><strong>${esc(label)}</strong><span>${pass?'Looks good':esc(tip)}</span></div></div>`).join('')}<div class="divider-space"></div><p class="panel-titleline">Compare to a job description</p><label class="field"><span>Paste the job listing to find shared keywords</span><textarea id="jobText" rows="6" placeholder="Paste the job description here...">${esc(jobText)}</textarea></label>${kws.length?`<p style="font-size:11px;color:#88859a;margin-bottom:11px">${kws.filter(x=>x.match).length} of ${kws.length} extracted keywords present. Review relevance before adding any.</p><div>${kws.map(k=>`<span class="keyword-chip ${k.match?'match':'miss'}">${esc(k.word)} ${k.match?'✓':'·'}</span>`).join('')}</div>`:''}<p class="footer-note">Keyword matching is a simple local text comparison. It does not represent an employer's actual ATS ranking.</p>`;}
function exportPanel(){return`<div class="info-card"><strong style="font-size:12px">Unlimited exports. No watermark.</strong><p>There are no premium templates or subscription fees. Keep editable backups with JSON.</p></div>${[['pdf','file','PDF document','Best for sharing · opens the browser print dialog'],['docx','document','Word document (.docx)','Editable, ATS-oriented single-column Word file'],['txt','text','Plain text (.txt)','Simple content for forms and applications'],['json','save','Editable backup (.json)','Import later to restore all resume details']].map(([type,ico,title,desc])=>`<button class="export-option" data-action="export" data-value="${type}"><span class="export-icon">${icon(ico,20)}</span><span style="flex:1"><strong>${title}</strong><small>${desc}</small></span>${icon('download',17)}</button>`).join('')}<p class="footer-note">PDF: choose “Save as PDF” in your browser's print dialog.</p>`;}
function sectionPreview(s){const d=doc(),items=s.items||[],subheading=`<h2>${esc(s.title)}</h2>`;let inner='';if(s.kind==='summary'){inner=items.filter(x=>x.text).map(x=>`<p class="res-paragraph">${esc(x.text)}</p>`).join('');}
 else if(s.kind==='tags'){const tags=items.flatMap(x=>(x.text||'').split(/[,\n]/).map(k=>k.trim()).filter(Boolean));inner=`<div class="res-tags">${tags.map(k=>`<span>${esc(k)}</span>`).join('')}</div>`;}
 else if(s.kind==='compact'){inner=items.filter(x=>Object.values(x).some(v=>String(v).trim())).map(it=>`<div class="res-compact"><strong>${esc(it.title||'')}</strong><div class="small">${esc([it.subtitle,it.date].filter(Boolean).join(' · '))}</div>${it.details?`<p class="res-paragraph">${esc(it.details)}</p>`:''}</div>`).join('');}
 else {inner=items.filter(it=>Object.values(it).some(v=>String(v).trim())).map(it=>`<div class="res-entry"><div class="res-entry-header"><span class="res-entry-title">${esc(it.title)}</span><span class="res-entry-date">${esc([it.start,it.end].filter(Boolean).join(' – '))}</span></div>${it.subtitle||it.location?`<div class="res-entry-sub">${esc(it.subtitle)}${it.location?`<span class="res-entry-location">${it.subtitle?' · ':''}${esc(it.location)}</span>`:''}</div>`:''}${it.details?`<ul class="res-bullets">${it.details.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>`<li>${esc(line.replace(/^[•\-]\s*/,''))}</li>`).join('')}</ul>`:''}</div>`).join('');}
 return`<section class="res-section" data-action="focusSection" data-sid="${s.id}" title="Click to edit ${esc(s.title)}">${subheading}${inner}</section>`;}
function previewMarkup(){const d=doc(),c=d.contact;const labels=[['mail','email'],['phone','phone'],['pin','location'],['link','website'],['link','linkedin'],['link','github']];const contact=labels.filter(([i,k])=>c[k]?.trim()).map(([i,k])=>`<span>${icon(i,11)}${esc(c[k])}</span>`).join('');const enabled=d.sections.filter(s=>s.visible);const isSplit=d.template==='split';const body=isSplit?`<div class="res-columns"><div>${enabled.filter(s=>s.column!=='side').map(sectionPreview).join('')}</div><div>${enabled.filter(s=>s.column==='side').map(sectionPreview).join('')}</div></div>`:enabled.map(sectionPreview).join('');return`<header class="res-head"><h1 class="res-name">${esc(c.fullName)||'Your Name'}</h1><div class="res-role">${esc(c.headline)||'Your Professional Title'}</div><div class="res-contact">${contact}</div></header>${body||'<div class="empty-page-hint">Use the editor to add your first section.</div>'}`;}
function renderPreview(){const p=$('#resumePaper');if(!p||!doc())return;const d=doc();p.className=`resume-paper template-${d.template==='minimal'?'classic':d.template} density-${d.density} font-${d.font} case-${d.headingCase}`;p.style.setProperty('--accent',safeColor(d.accent));p.style.fontSize=`${Number(d.fontSize)||12}px`;p.style.width=d.paper==='a4'?'794px':'816px';p.style.minHeight=d.paper==='a4'?'1123px':'1056px';p.innerHTML=previewMarkup();syncZoom();const label=$('#pageLabel');if(label)label.textContent=d.paper==='a4'?'A4':'US Letter';}
function syncZoom(){const scroller=$('#paperScroller'),holder=$('#paperHolder'),paper=$('#resumePaper');if(!scroller||!holder||!paper||!doc())return;const width=doc().paper==='a4'?794:816;const height=Math.max(doc().paper==='a4'?1123:1056,paper.scrollHeight);let scale=zoomSetting==='fit'?Math.min(1,(scroller.clientWidth-36)/width):zoomSetting;scale=Math.min(Math.max(scale,.35),1.5);paper.style.transform=`scale(${scale})`;paper.style.transformOrigin='top left';holder.style.width=`${width*scale}px`;holder.style.height=`${height*scale}px`;const label=$('#zoomLabel');if(label)label.textContent=`${Math.round(scale*100)}%`;}
function findSection(id){return doc()?.sections.find(s=>s.id===id)}
function flipEntry(id,index,dir){const s=findSection(id),next=index+dir;if(!s||next<0||next>=s.items.length)return;[s.items[index],s.items[next]]=[s.items[next],s.items[index]];changed();renderPanel();renderPreview();}
function moveSection(id,dir){const secs=doc().sections,i=secs.findIndex(s=>s.id===id),n=i+dir;if(i<0||n<0||n>=secs.length)return;[secs[i],secs[n]]=[secs[n],secs[i]];changed();renderPanel();renderPreview();}
function createDoc(blank=true){const d=blank?blankDocument():demoDocument();store.docs.push(d);persist();activeId=d.id;tab='content';openSection=d.sections[0]?.id||null;mobilePreview=false;zoomSetting='fit';renderEditor();showToast('Your new resume is ready');}
function duplicateResume(id){const d=store.docs.find(x=>x.id===id);if(!d)return;const copy=JSON.parse(JSON.stringify(d));copy.id=uid();copy.title=d.title+' (copy)';copy.updated=Date.now();copy.sections.forEach(s=>s.id=uid());store.docs.push(copy);persist();if(activeId===id){activeId=copy.id;renderEditor();}else renderDashboard();showToast('Resume duplicated');}
function openModal(name){modalName=name;const content=name==='add'?`<div class="modal-head"><h2>Add a resume section</h2><button class="icon-btn" data-action="closeModal" aria-label="Close">${icon('close',17)}</button></div><div class="modal-body"><p style="font-size:12px;color:#8e8a9d;margin-bottom:17px">Choose from common sections, or add your own custom content.</p><div class="add-section-grid">${sectionDefs.map(([id,title])=>`<button class="add-type" data-action="addSection" data-value="${id}">${icon(id==='experience'?'briefcase':id==='education'?'school':id==='skills'?'sparkle':'file',17)} ${esc(title)}</button>`).join('')}</div></div>`:name==='delete'?`<div class="modal-head"><h2>Delete this resume?</h2><button class="icon-btn" data-action="closeModal">${icon('close',17)}</button></div><div class="modal-body" style="color:#797589;font-size:13px;line-height:1.6">This will permanently remove the resume from this browser. Export a JSON backup first if you might need it.</div><div class="modal-foot"><button class="btn white" data-action="closeModal">Cancel</button><button class="btn danger" data-action="confirmDelete">Delete resume</button></div>`:'';const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.id='appModal';overlay.innerHTML=`<div class="modal" role="dialog" aria-modal="true">${content}</div>`;document.body.appendChild(overlay);}
function closeModal(){modalName=null;$('#appModal')?.remove();}
let deleteTarget=null;
function safeFilename(d){return(d.contact.fullName||d.title||'resume').trim().replace(/[^a-zA-Z0-9_\-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,75)||'resume';}
function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportText(d){let lines=[d.contact.fullName,d.contact.headline,[d.contact.email,d.contact.phone,d.contact.location,d.contact.website,d.contact.linkedin,d.contact.github].filter(Boolean).join(' | ')];for(const s of d.sections.filter(s=>s.visible)){lines.push('',s.title.toUpperCase());for(const item of s.items){if(s.kind==='summary'||s.kind==='tags')lines.push(item.text||'');else if(s.kind==='compact'){lines.push([item.title,item.subtitle,item.date].filter(Boolean).join(' | '));if(item.details)lines.push(item.details);}else{lines.push([item.title,item.subtitle,item.location].filter(Boolean).join(' | '));lines.push([item.start,item.end].filter(Boolean).join(' – '));if(item.details)lines.push(...item.details.split('\n').filter(Boolean).map(s=>'• '+s.replace(/^[•-]\s*/,'')));}}}return lines.join('\n').replace(/\n{3,}/g,'\n\n').trim()+'\n';}
function exportPdf(){const paper=$('#resumePaper');if(!paper)return;const mount=$('#printMount');mount.innerHTML=paper.outerHTML;const cloned=mount.firstElementChild;cloned.removeAttribute('id');cloned.style.transform='none';cloned.style.width='100%';cloned.style.minHeight='0';const pg=$('#dynamicPrintPage')||document.head.appendChild(Object.assign(document.createElement('style'),{id:'dynamicPrintPage'}));pg.textContent=`@media print { @page {size:${doc().paper==='a4'?'A4':'letter'};margin:0;} }`;document.body.classList.add('printing');window.print();setTimeout(()=>document.body.classList.remove('printing'),1500);showToast('Choose Save as PDF in the print dialog');}
function exportJson(){downloadBlob(new Blob([JSON.stringify(doc(),null,2)],{type:'application/json'}),safeFilename(doc())+'.json');}
function exportFile(type){const d=doc();if(!d)return;if(type==='pdf')return exportPdf();if(type==='txt')return downloadBlob(new Blob([exportText(d)],{type:'text/plain;charset=utf-8'}),safeFilename(d)+'.txt');if(type==='json')return exportJson();if(type==='docx'){downloadBlob(makeDocx(d),safeFilename(d)+'.docx');showToast('Word document downloaded');}}
function validateImport(input){if(!input||typeof input!=='object'||!input.contact||!Array.isArray(input.sections))throw Error('Not a recognized resume backup');const d=blankDocument();d.title=String(input.title||'Imported resume').slice(0,80);for(const key of Object.keys(d.contact))d.contact[key]=String(input.contact[key]??'').slice(0,10000);for(const key of ['template','font','density','paper','headingCase'])if(typeof input[key]==='string'&&input[key].length<50)d[key]=input[key];if(!['split','clean','classic','minimal'].includes(d.template))d.template='clean';if(!['sans','serif','modern'].includes(d.font))d.font='sans';if(!['compact','normal','spacious'].includes(d.density))d.density='normal';if(!['letter','a4'].includes(d.paper))d.paper='letter';if(!['upper','natural'].includes(d.headingCase))d.headingCase='upper';d.accent=safeColor(input.accent);d.fontSize=[10,11,12,13,14].includes(Number(input.fontSize))?Number(input.fontSize):12;d.sections=input.sections.slice(0,70).map(s=>{const kind=['summary','tags','compact','timeline'].includes(s.kind)?s.kind:'summary';const fields=kind==='timeline'?['title','subtitle','location','start','end','details']:kind==='compact'?['title','subtitle','date','details']:['text'];return{id:uid(),type:String(s.type||'custom').slice(0,60),kind,title:String(s.title||'Custom section').slice(0,100),column:s.column==='side'?'side':'main',visible:s.visible!==false,items:Array.isArray(s.items)?s.items.slice(0,100).map(i=>Object.fromEntries(fields.map(k=>[k,String(i?.[k]||'').slice(0,25000)]))):[defaultItem(kind)]};});return d;}
// ---------------------------- Native DOCX writer (OOXML, no dependencies) ----------------------------
const uint16=n=>[n&255,(n>>>8)&255],uint32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
const enc=new TextEncoder();
let crcTable;
function crc32(bytes){if(!crcTable)crcTable=Array.from({length:256},(_,i)=>{let c=i;for(let k=0;k<8;k++)c=c&1?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0;});let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
function zipFiles(files){const parts=[],central=[];let offset=0;for(const [filename,contents] of Object.entries(files)){const name=enc.encode(filename),body=enc.encode(contents),crc=crc32(body),local=new Uint8Array([80,75,3,4,20,0,0,0,0,0,0,0,0,0,...uint32(crc),...uint32(body.length),...uint32(body.length),...uint16(name.length),0,0]);parts.push(local,name,body);central.push(new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0,0,0,...uint32(crc),...uint32(body.length),...uint32(body.length),...uint16(name.length),0,0,0,0,0,0,0,0,0,0,0,0,...uint32(offset)]),name);offset+=local.length+name.length+body.length;}const centralSize=central.reduce((n,p)=>n+p.length,0);const count=Object.keys(files).length;return new Blob([...parts,...central,new Uint8Array([80,75,5,6,0,0,0,0,...uint16(count),...uint16(count),...uint32(centralSize),...uint32(offset),0,0])],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});}
function makeDocx(d){const run=(str,bold=false)=>`<w:r>${bold?'<w:rPr><w:b/></w:rPr>':''}<w:t xml:space="preserve">${xesc(str)}</w:t></w:r>`;const para=(str,style='Normal',bold=false)=>`<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr>${run(str,bold)}</w:p>`;const blank=()=>'<w:p/>';const blocks=[];blocks.push(para(d.contact.fullName||'Your Name','Name'));blocks.push(para(d.contact.headline||'','Subtitle'));blocks.push(para([d.contact.email,d.contact.phone,d.contact.location].filter(Boolean).join('  |  '),'Contact'));blocks.push(para([d.contact.website,d.contact.linkedin,d.contact.github].filter(Boolean).join('  |  '),'Contact'));for(const s of d.sections.filter(x=>x.visible)){blocks.push(para(s.title.toUpperCase(),'Heading1'));for(const item of s.items){if(s.kind==='summary'){for(const line of (item.text||'').split(/\n/))if(line.trim())blocks.push(para(line));}else if(s.kind==='tags'){blocks.push(para((item.text||'').replace(/\n/g,', ')));}else if(s.kind==='compact'){if(item.title)blocks.push(para(item.title,'EntryTitle'));if(item.subtitle||item.date)blocks.push(para([item.subtitle,item.date].filter(Boolean).join(' · '),'Detail'));if(item.details)for(const line of item.details.split('\n'))if(line.trim())blocks.push(para(line));}else{if(item.title)blocks.push(para([item.title,[item.start,item.end].filter(Boolean).join(' – ')].filter(Boolean).join('   |   '),'EntryTitle'));if(item.subtitle||item.location)blocks.push(para([item.subtitle,item.location].filter(Boolean).join(' · '),'Detail'));for(const line of (item.details||'').split(/\n/)){if(line.trim())blocks.push(para('•  '+line.replace(/^[•\-]\s*/,''),'Bullet'));}}}blocks.push(blank());}
 const pg=d.paper==='a4'?'<w:pgSz w:w="11906" w:h="16838"/>':'<w:pgSz w:w="12240" w:h="15840"/>';
 const documentXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${blocks.join('')}<w:sectPr>${pg}<w:pgMar w:top="720" w:right="850" w:bottom="720" w:left="850" w:header="360" w:footer="360" w:gutter="0"/></w:sectPr></w:body></w:document>`;
 const accent=safeColor(d.accent).slice(1).toUpperCase();const family=d.font==='serif'?'Georgia':d.font==='modern'?'Trebuchet MS':'Arial';const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="${family}" w:hAnsi="${family}"/><w:sz w:val="21"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="60"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Name"><w:name w:val="Name"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="40"/></w:pPr><w:rPr><w:b/><w:sz w:val="34"/><w:color w:val="292837"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="23"/><w:color w:val="${accent}"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Contact"><w:name w:val="Contact"/><w:basedOn w:val="Normal"/><w:rPr><w:sz w:val="18"/><w:color w:val="686878"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:before="260" w:after="100"/><w:keepNext/><w:pBdr><w:bottom w:val="single" w:sz="8" w:color="${accent}"/></w:pBdr></w:pPr><w:rPr><w:b/><w:sz w:val="22"/><w:color w:val="${accent}"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="EntryTitle"><w:name w:val="Entry Title"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="100" w:after="30"/></w:pPr><w:rPr><w:b/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Detail"><w:name w:val="Detail"/><w:basedOn w:val="Normal"/><w:rPr><w:color w:val="${accent}"/><w:sz w:val="19"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Bullet"><w:name w:val="Bullet"/><w:basedOn w:val="Normal"/><w:pPr><w:ind w:left="280" w:hanging="160"/><w:spacing w:after="40"/></w:pPr></w:style></w:styles>`;
 return zipFiles({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/_rels/document.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>','word/document.xml':documentXml,'word/styles.xml':styles});}
// ---------------------------- events ----------------------------
$('#importInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const d=validateImport(data);store.docs.push(d);persist();activeId=d.id;tab='content';openSection=d.sections[0]?.id||null;renderEditor();showToast('Resume imported successfully');}catch(err){alert('Import failed: '+err.message);}e.target.value='';});
document.addEventListener('input',e=>{const target=e.target;if(target.id==='jobText'){jobText=target.value;const pos=target.selectionStart;const parent=$('#panelContent');if(!parent)return;/* keep textarea focus while updating keywords only on blur */return;}
 const object=target.dataset.object,key=target.dataset.key;if(!object||!doc())return;const value=target.value;let context;if(object==='contact')context=doc().contact;else if(object==='document')context=doc();else if(object==='section')context=findSection(target.dataset.sid);else if(object==='item')context=findSection(target.dataset.sid)?.items[Number(target.dataset.index)];if(!context)return;context[key]=key==='fontSize'?Number(value):value;changed();renderPreview();});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='jobText'){jobText=t.value;renderPanel();return;}if(!t.dataset.object||!doc())return;const object=t.dataset.object,key=t.dataset.key;let ctx=object==='document'?doc():object==='section'?findSection(t.dataset.sid):object==='contact'?doc().contact:null;if(!ctx)return;ctx[key]=key==='fontSize'?Number(t.value):t.value;changed();renderPreview();if(['font','fontSize','accent','column'].includes(key))renderPanel();});
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))return closeModal();const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,sid=el.dataset.sid,value=el.dataset.value,id=el.dataset.id;switch(action){
 case'newResume':createDoc();break;
 case'editResume':activeId=id;tab='content';openSection=doc()?.sections[0]?.id||null;mobilePreview=false;zoomSetting='fit';renderEditor();break;
 case'dashboard':renderDashboard();break;
 case'setTab':tab=el.dataset.tab;mobilePreview=false;renderEditor();break;
 case'toggleSection':openSection=openSection===sid?null:sid;renderPanel();break;
 case'focusSection':tab='content';openSection=sid;mobilePreview=false;renderEditor();setTimeout(()=>$('#edit-'+sid)?.scrollIntoView({block:'nearest',behavior:'smooth'}),100);break;
 case'openAddModal':openModal('add');break;
 case'closeModal':closeModal();break;
 case'addSection':{const s=newSection(value);doc().sections.push(s);openSection=s.id;tab='content';changed();closeModal();renderEditor();setTimeout(()=>$('#edit-'+s.id)?.scrollIntoView({block:'nearest',behavior:'smooth'}),100);break;}
 case'addEntry':{const s=findSection(sid);s?.items.push(defaultItem(s.kind));changed();renderPanel();renderPreview();break;}
 case'removeEntry':{const s=findSection(sid);if(s){s.items.splice(Number(el.dataset.index),1);changed();renderPanel();renderPreview();}break;}
 case'moveEntry':flipEntry(sid,Number(el.dataset.index),Number(el.dataset.direction));break;
 case'moveSection':moveSection(sid,Number(el.dataset.direction));break;
 case'toggleVisibility':{const s=findSection(sid);if(s){s.visible=!s.visible;changed();renderPanel();renderPreview();}break;}
 case'removeSection':{const s=findSection(sid);if(s&&confirm(`Remove ${s.title} and its entries?`)){doc().sections=doc().sections.filter(x=>x.id!==sid);changed();renderPanel();renderPreview();}break;}
 case'setTemplate':doc().template=value;changed();renderPanel();renderPreview();break;
 case'setAccent':doc().accent=value;changed();renderPanel();renderPreview();break;
 case'setDensity':doc().density=value;changed();renderPanel();renderPreview();break;
 case'setPaper':doc().paper=value;changed();renderPanel();renderPreview();break;
 case'setCase':doc().headingCase=value;changed();renderPanel();renderPreview();break;
 case'duplicate':duplicateResume(id);break;
 case'deleteResume':deleteTarget=id;openModal('delete');break;
 case'confirmDelete':{store.docs=store.docs.filter(d=>d.id!==deleteTarget);persist();closeModal();renderDashboard();showToast('Resume deleted');break;}
 case'export':exportFile(value);break;
 case'import':$('#importInput').click();break;
 case'zoomIn':zoomSetting=zoomSetting==='fit'?Math.min(1.5,(parseInt($('#zoomLabel').textContent)/100)+.1):Math.min(1.5,zoomSetting+.1);syncZoom();break;
 case'zoomOut':zoomSetting=zoomSetting==='fit'?Math.max(.35,(parseInt($('#zoomLabel').textContent)/100)-.1):Math.max(.35,zoomSetting-.1);syncZoom();break;
 case'mobilePreview':mobilePreview=!mobilePreview;$('.editor-body')?.classList.toggle('mobile-preview',mobilePreview);requestAnimationFrame(syncZoom);break;
 }});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();persist();showToast('Saved locally');}});
window.addEventListener('resize',()=>requestAnimationFrame(syncZoom));
window.addEventListener('afterprint',()=>document.body.classList.remove('printing'));
renderDashboard();
